AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 instance with Apache web server

Resources:
  WebServerInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0c02fb55956c7d316  # Amazon Linux 2 (us-east-1)
      InstanceType: t2.micro
      KeyName: braj-ec2-key.pem
      SecurityGroups: [!Ref WebServerSG]
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y httpd
          systemctl start httpd
          systemctl enable httpd
          echo "Hello from GitHub Actions via CloudFormation!" > /var/www/html/index.html

  WebServerSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

